[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = dpg-d806dp3eo5us73f8huhg-a
db_port = 5432
db_user = odoo_db_9mk7_user
db_password = Sfx1GcPbytXMFTfYe85BueHxahoZ9QvV
db_name = odoo
http_port = 8069
